version: '3.4'

services:
  api:
    image: ${DOCKER_REGISTRY-}api
    container_name: Api
    build:
      context: .
      dockerfile: src/Api/Dockerfile
    depends_on:
      - db
      - idp


  db:
    image: postgres:latest
    container_name: Db
    environment:
      - POSTGRES_DB=bookify
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./.containers/database:/var/lib/postgresql/data
    ports:
      - 5432:5432

  idp:
    image: jboss/keycloak:latest
    container_name: Identity
    environment:
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=admin
      - KEYCLOAK_IMPORT=/tmp/realm-export.json
    volumes:
      - ./.containers/identity:/opt/jboss/keycloak/standalone/data
      - ./.files/realm-export.json:/tmp/realm-export.json
    ports:
      - 18080:8080

  seq:
    image: datalust/seq:latest
    container_name: Seq
    environment:
      - ACCEPT_EULA=Y
    ports:
      - 5341:5341
      - 8081:80

  redis:
    image: redis/redis-stack
    container_name: Redis
    restart: always
    ports:
      - '6379:6379'
      - '8001:8001'