version: '3.4'

services:
  api:
    image: ${DOCKER_REGISTRY-}api
    container_name: Api
    build:
      context: .
      dockerfile: src/Api/Dockerfile
    depends_on:
     - db
     - idp

  db:
    image: postgres:latest
    container_name: Db
    environment:
     - POSTGRES_DB=bookify
     - POSTGRES_USER=postgres
     - POSTGRES_PASSWORD=postgres
    volumes:
     - ./.containers/database:/var/lib/postgresql/data
    ports:
     - 5432:5432
  
  idp:
    image: jboss/keycloak:latest
    container_name: Identity
    environment:
     - KEYCLOAK_USER=admin
     - KEYCLOAK_PASSWORD=admin  
     - KEYCLOAK_IMPORT=/tmp/bookify-realm-export.json
    volumes:
     - ./.containers/identity:/opt/jboss/keycloak/standalone/data
     - ./.files/bookify-realm-export.json:/tmp/bookify-realm-export.json
    ports:
     - 18080:8080