version: '3.4'

services:
  api:
    image: ${DOCKER_REGISTRY-}api
    container_name: Api
    build:
      context: .
      dockerfile: src/Api/Dockerfile
    depends_on:
     - db

  db:
    image: postgres:latest
    container_name: Db
    environment:
     - POSTGRES_DB=bookify
     - POSTGRES_USER=postgres
     - POSTGRES_PASSWORD=postgres
    volumes:
     - ./.containers/database:/var/lib/postgresql/data
    ports:
     - 5432:5432
